---
title: „Finally“ darf in einer Try-Anweisung nur einmal angegeben werden.
ms.date: 07/20/2015
f1_keywords:
- vbc30381
- bc30381
helpviewer_keywords:
- BC30381
ms.assetid: 4fa1d5fa-c54a-4f8c-9d66-9dbcc38c53bf
ms.openlocfilehash: c6338b3d9be4378ee5e3a068f4642d6b84d1e645
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 09/23/2020
ms.locfileid: "91074536"
---
# <a name="finally-can-only-appear-once-in-a-try-statement"></a>„Finally“ darf in einer Try-Anweisung nur einmal angegeben werden.

`Finally` wird zum Beenden eines `Try...Catch...Finally` -Blocks verwendet und kann daher nur einmal am Ende des Blocks angegeben werden.  
  
 **Fehler-ID:** BC30381  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1. Suchen und entfernen Sie das redundante `Finally`.  
  
## <a name="see-also"></a>Siehe auch

- [Try... Catch... Abschließend-Anweisung](../language-reference/statements/try-catch-finally-statement.md)
