---
title: Der Catch-Block wird niemals erreicht; "<exception>" wird oben in der gleichen Try-Anweisung behandelt
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 5133bfd9b4471350691407dee09feec2d3af444a
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 09/23/2020
ms.locfileid: "91084553"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a><span data-ttu-id="8050d-102">Der Catch-Block wird niemals erreicht; "\<exception>" wird oben in der gleichen Try-Anweisung behandelt</span><span class="sxs-lookup"><span data-stu-id="8050d-102">'Catch' block never reached; \<exception> handled above in the same 'Try' statement</span></span>

<span data-ttu-id="8050d-103">Ein `Catch` -Block im Code kann nicht erreicht werden, weil er in einem vorhergehenden `Try` -Block behandelt wird.</span><span class="sxs-lookup"><span data-stu-id="8050d-103">A `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block.</span></span>  
  
<span data-ttu-id="8050d-104">Standardmäßig ist diese Meldung eine Warnung.</span><span class="sxs-lookup"><span data-stu-id="8050d-104">By default, this message is a warning.</span></span> <span data-ttu-id="8050d-105">Weitere Informationen zum Ausblenden von Warnungen oder zum Behandeln von Warnungen als Fehler finden Sie unter [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).</span><span class="sxs-lookup"><span data-stu-id="8050d-105">For more information about hiding warnings or treating warnings as errors, see [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).</span></span>
  
 <span data-ttu-id="8050d-106">**Fehler-ID:** BC42031</span><span class="sxs-lookup"><span data-stu-id="8050d-106">**Error ID:** BC42031</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="8050d-107">So beheben Sie diesen Fehler</span><span class="sxs-lookup"><span data-stu-id="8050d-107">To correct this error</span></span>  
  
- <span data-ttu-id="8050d-108">Entfernen Sie die redundante Anweisung.</span><span class="sxs-lookup"><span data-stu-id="8050d-108">Remove the redundant statement.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="8050d-109">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="8050d-109">See also</span></span>

- [<span data-ttu-id="8050d-110">Verwenden des try/catch-Blocks zum Abfangen von Ausnahmen</span><span class="sxs-lookup"><span data-stu-id="8050d-110">How to use the try/catch block to catch exceptions</span></span>](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [<span data-ttu-id="8050d-111">Verwenden benutzergefilterter Ausnahmehandler</span><span class="sxs-lookup"><span data-stu-id="8050d-111">Using User-Filtered Exception Handlers</span></span>](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [<span data-ttu-id="8050d-112">Try... Catch... Abschließend-Anweisung</span><span class="sxs-lookup"><span data-stu-id="8050d-112">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
