---
description: Compilerfehler CS0103
title: Compilerfehler CS0103
ms.date: 07/20/2015
f1_keywords:
- CS0103
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
ms.openlocfilehash: 689cebb258fcd75287e8e54630387ae7a6e986c5
ms.sourcegitcommit: d579fb5e4b46745fd0f1f8874c94c6469ce58604
ms.translationtype: HT
ms.contentlocale: de-DE
ms.lasthandoff: 08/30/2020
ms.locfileid: "89134730"
---
# <a name="compiler-error-cs0103"></a>Compilerfehler CS0103

Der Name „identifier“ ist im aktuellen Kontext nicht vorhanden.

 Es wurde versucht, einen Namen zu verwenden, der nicht in der Klasse, im [Namespace](../keywords/namespace.md) oder im Gültigkeitsbereich vorhanden ist. Überprüfen Sie die Schreibweise des Namens und die using-Anweisungen und Assemblyverweise, um sicherzustellen, dass der Name, den Sie verwenden möchten, verfügbar ist.

 Dieser Fehler tritt häufig auf, wenn Sie eine Variable in einer Schleife oder einem `try`- oder `if`-Block deklarieren und dann versuchen, von einem einschließenden Codeblock oder einem separaten Codeblock darauf zuzugreifen, wie im folgenden Beispiel gezeigt:

```csharp
using System;

class MyClass1
{
    public static void Main()
    {
        try
        {
            // The following declaration is only available inside the try block.
            var conn = new MyClass1();
        }
        catch (Exception e)
        {  
            // The following expression causes error CS0103, because variable
            // conn only exists in the try block.
            if (conn != null)
                Console.WriteLine("{0}", e);
        }
    }
}
```

 Im folgende Beispiel wird der Fehler behoben:

```csharp
using System;

class MyClass2
{
    public static void Main()
    {
        // To resolve the error in the example, the first step is to
        // move the declaration of conn out of the try block. The following
        // declaration is available throughout the Main method.
        MyClass2 conn = null;
        try
        {
            // Inside the try block, use the conn variable that you declared
            // previously.
            conn = new MyClass2();
        }
        catch (Exception e)
        {
            // The following expression no longer causes an error, because
            // the declaration of conn is in scope.
            if (conn != null)
                Console.WriteLine("{0}", e);
        }
    }
}
```
